source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YJKit_Example', :exclusive => true do
  pod 'YJKit', :path => '../'
end

target 'YJKit_Tests', :exclusive => true do
  pod 'YJKit', :path => '../'

  
end
